.ds q \N'34'
.TH versionn 1 "2014-10-03" "v0.0.2" "versionn.js"

.SH NAME
versionn \- set semver version across multiple files

.SH SYNOPSIS
.B versionn
[\-\-premajor|\-\-preminor|\-\-prepatch|\-\-prerelease|\-\-major|\-\-minor|\-\-patch|\-\-pre] 
[\-e \fI<file>\fP] 
[\-d \fI<dir>\fP]
[\-t] [\-u] [\-\-help] [\-\-version] [\fIfilenames\fP]

.SH DESCRIPTION
.B versionn
is a tool to set the same semver based version number accross multiple files.

.SH EXAMPLES
.TP
versionn
.TP.TP
Increments the `patch` version of `VERSION`, `package.json`, `bower.json`, `component.json`.
.TP
versionn --minor package.json
.TP.TP
Increment the `minor` version of `package.json` only.
.TP
versionn --premajor -e VERSION bower.json component.json
.TP.TP
Extract the version from `VERSION` and increase `bower.json` and `component.json` by `premajor` version. Note: `VERSION` will *NOT* be increased!
.TP
versionn -d <otherdir>
.TP.TP
Choose a different directory other that the current-working-directory:
.TP
versionn -t
.TP.TP
Git-tag the version 
versionn -u
.TP.TP
Remove the Git-tag of the current version

.SH OPTIONS
.TP
.BI \-\-premajor|\-\-preminor|\-\-prepatch|\-\-prerelease|\-\-major|\-\-minor|\-\-patch|\-\-pre
Increase the version by ...
.TP
.BI \-e,\ \-\-extract\ \fI<file>\fP
Extract version information from <file>
.TP
.BI \-d,\ \-\-dir\ \fI<dir>\fP
Apply versionn in directory <dir>
.TP
.BI \-t,\ \-\-tag
Set Git version tag
.TP
.BI \-u,\ \-\-untag
Unset Git version tag
.TP
.BI \-h,\ \-\-help
Display help information.
.TP
.BI \ \-\-version
Display version.


.SH BUGS
Please report any bugs to https://github.com/commenthol/versionn.

.SH LICENSE
Copyright (c) 2014-, commenthol (MIT License).

.SH "SEE ALSO"
.BR node.js(1)
